### ISSUE TITLE
Update notebook to use Featuretools Dask Implementation

### ISSUE THREAD

**Issue by kmax12** [Featuretools/predict-next-purchase#16]
After https://github.com/FeatureLabs/featuretools/pull/783 is merged, we can update the notebook to the improved api

**Comment by thehomebrewnerd** [comment]
Added a branch called `add-dask-example` that contains a notebook that shows how to generate a feature matrix using Dask EntitySets. Once [Featuretools Issue 783](https://github.com/FeatureLabs/featuretools/pull/783) is complete, this notebook should be reviewed and updated as needed before being merged into `master`. Currently this notebook requires users to install Featuretools from the `dask-entity` branch to run.
