### ISSUE TITLE
AssertionError: target columns not found

### ISSUE THREAD

**Issue by lxqpku** [Featuretools/predict-next-purchase#19]
After features are generated, there's AssertionError: target columns not found

**Comment by world4jason** [comment]
same issue here, i think the problem comes from here
https://github.com/Featuretools/predict-next-purchase/blob/main/utils.py#L79

**Comment by world4jason** [comment]
X = fm_encoded.reset_index().merge(label_times,on="user_id")
X.drop(["user_id", "time"], axis=1, inplace=True)
X = X.fillna(0)
y = X.pop("bought_product_y").astype('bool')

these changes work for me
